language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy

#virtualenv:
#  system_site_packages: true

before_install:
  - sudo apt-get install python-yaml python3-yaml
install:
  - export PYTHONIOENCODING=UTF8
  - python setup.py install
  - pip install coveralls --use-mirrors

before_script:
  - source test.env
script:
  - coverage run tools/testall.py

after_success:
  - coverage combine
  - coveralls
