language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - pypy

install:
  - export PYTHONIOENCODING=UTF8
  - pip install coveralls pytest-cov ptyprocess

script:
    - ./tools/display-sighandlers.py
    - ./tools/display-terminalinfo.py
    - py.test --cov pexpect --cov-config .coveragerc

after_success:
  - coverage combine
  - coveralls

# Use new Travis stack, should be faster
sudo: false
